
import Head from 'next/head'
import Aboutus from '../components/Aboutus'


export default function About() {
  return (
    <>
      <Head>
        <title>about us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       
       <Aboutus/>
      
      </main>
    </>
  )
}
