import Landingpage from '../components/Landingpage'
import Navar from '../components/Navar'
import Head from 'next/head'
import Service from '../components/Service'
import Contact from '../components/Contact'
import Aboutourservice from '../components/Aboutourservice'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       <Landingpage/>
       <Service/>
       <Aboutourservice/>
       <Contact/>
      
      </main>
    </>
  )
}
